---
- name: Restart prometheus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
  register: prometheus_restarted

- name: Reload prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
  when: prometheus_restarted is not defined
